apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/app-configs/nvidia-gpu-verification/overlays/default?ref=v0.19

patches:
  - path: patch-deploy.yaml
  - path: patch-pod.yaml
